#include QMK_KEYBOARD_H


#define _LAYER0 0
#define _LAYER1 1
#define _LAYER2 2
#define _LAYER3 3

enum custom_keycodes {
    LAYER0 = SAFE_RANGE,
    LAYER1,
    LAYER2,
    LAYER3,
};

 const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

 [_LAYER0] = LAYOUT(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_DEL, KC_Y, KC_C, KC_L, KC_M, KC_K, KC_Z, KC_F, KC_U, KC_COMM, KC_QUOT, KC_GRV, KC_LSFT, KC_I, KC_S, KC_R, KC_T, KC_G, KC_P, KC_N, KC_E, KC_A, KC_O, KC_SCLN, KC_TRNS, KC_Q, KC_V, KC_W, KC_D, KC_J, KC_B, KC_H, KC_SLSH, KC_DOT, KC_X, KC_TRNS, KC_LBRC, KC_RBRC, KC_MINS, KC_EQL, LALT_T(KC_ENT), LT(1,KC_SPC), OSL(2), LT(3,KC_BSPC), KC_TRNS, KC_ESC, OSM(MOD_LSFT), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

[_LAYER1] = LAYOUT(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LCTL(KC_Y), LCTL(KC_C), LCTL(KC_L), LCTL(KC_M), LCTL(KC_K), LCTL(KC_Z), LCTL(KC_F), LCTL(KC_U), LCTL(KC_COMM), LCTL(KC_QUOT), LCTL(KC_GRV), KC_TRNS, LCTL(KC_I), LCTL(KC_S), LCTL(KC_R), LCTL(KC_T), LCTL(KC_G), LCTL(KC_P), LCTL(KC_N), LCTL(KC_E), LCTL(KC_A), LCTL(KC_O), LCTL(KC_SCLN), KC_TRNS, LCTL(KC_Q), LCTL(KC_V), LCTL(KC_W), LCTL(KC_D), LCTL(KC_J), LCTL(KC_B), LCTL(KC_H), LCTL(KC_SLSH), LCTL(KC_DOT), LCTL(KC_X), KC_TRNS, LCTL(KC_LBRC), LCTL(KC_RBRC), LCTL(KC_MINS), LCTL(KC_EQL), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

[_LAYER2] = LAYOUT(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LBRC, KC_RBRC, KC_TRNS, KC_TRNS, KC_LT, KC_GT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_UNDS, KC_DLR, KC_LPRN, KC_RPRN, KC_AMPR, KC_HASH, KC_EQL, KC_MINS, KC_PLUS, KC_EXLM, KC_TRNS, KC_TRNS, KC_AT, KC_PERC, KC_LCBR, KC_RCBR, KC_TRNS, KC_TRNS, KC_DLR, KC_SLSH, KC_ASTR, KC_CIRC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

[_LAYER3] = LAYOUT(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_SLSH, KC_ASTR, KC_PDOT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PDOT, KC_ASTR, KC_SLSH, KC_TRNS, KC_5, KC_1, KC_2, KC_3, KC_4, KC_EQL, KC_EQL, KC_6, KC_7, KC_8, KC_9, KC_5, KC_TRNS, KC_TRNS, KC_EQL, KC_MINS, KC_0, KC_TRNS, KC_TRNS, KC_0, KC_MINS, KC_PLUS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_ENT, KC_SPC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS) 

};
